######################################################################
#
# File name : tb_par_product_calc.udo
# Created on: Mon Jan 22 19:38:49 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
