######################################################################
#
# File name : tb_par_product_calc_simulate.do
# Created on: Mon Jan 22 20:25:37 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_par_product_calc xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_par_product_calc_wave.do}

view wave
view structure
view signals

do {tb_par_product_calc.udo}

run 1000ns
