######################################################################
#
# File name : tb_wallace_mul_wave.do
# Created on: Mon Jan 22 15:00:01 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
