######################################################################
#
# File name : tb_wallace_mul_compile.do
# Created on: Mon Jan 22 20:30:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../../rtl/adder/full_adder.v" \
"../../../../../../rtl/adder/half_adder.v" \
"../../../../../../rtl/encoder/modefied_booth_enc.v" \
"../../../../../../rtl/par_product/par_product_add.v" \
"../../../../../../rtl/par_product/par_product_calc.v" \
"../../../../../../rtl/par_product/par_product_gen.v" \
"../../../../../../rtl/wallace_mul.v" \
"../../../../../../sim/tb/testbeach.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

