######################################################################
#
# File name : tb_wallace_mul.udo
# Created on: Tue Jan 23 15:44:16 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
