######################################################################
#
# File name : tb_wallace_mul_compile.do
# Created on: Tue Jan 23 15:44:11 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"tb_wallace_mul_func_synth.v" \
"../../../../../../../rtl/adder/adder4.v" \
"../../../../../../../rtl/adder/cla_32bits.v" \
"../../../../../../../rtl/adder/full_adder.v" \
"../../../../../../../rtl/adder/half_adder.v" \
"../../../../../../../rtl/encoder/modefied_booth_enc.v" \
"../../../../../../../rtl/par_product/par_product_add.v" \
"../../../../../../../rtl/par_product/par_product_calc.v" \
"../../../../../../../rtl/par_product/par_product_gen.v" \
"../../../../../../../rtl/wallace_mul.v" \
"../../../../../../../sim/tb/tb_wallace_tree.v" \


quit -force

