######################################################################
#
# File name : tb_wallace_mul_wave.do
# Created on: Tue Jan 23 15:44:16 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
