######################################################################
#
# File name : tb_wallace_mul_simulate.do
# Created on: Tue Jan 23 15:44:16 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_wallace_mul xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_wallace_mul_wave.do}

view wave
view structure
view signals

do {tb_wallace_mul.udo}

run 1000ns
