######################################################################
#
# File name : tb_wallace_mul_wave.do
# Created on: Mon Jan 22 20:51:19 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
