######################################################################
#
# File name : tb_wallace_mul_simulate.do
# Created on: Tue Jan 23 16:27:32 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_wallace_mul xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_wallace_mul_wave.do}

view wave
view structure
view signals

do {tb_wallace_mul.udo}

run 1000ns
