######################################################################
#
# File name : tb_wallace_mul_compile.do
# Created on: Mon Jan 22 20:51:16 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"tb_wallace_mul_time_impl.v" \
"../../../../../../../sim/tb/testbeach.v" \


quit -force

