######################################################################
#
# File name : tb_wallace_mul_wave.do
# Created on: Mon Jan 22 20:46:05 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
